### ISSUE TITLE
step 5 problem

### ISSUE THREAD

**Issue by dharniNO1** [tsycnh/WeChatExporter#30]
> sqlite3@4.1.1 install /Users/dharni/WeChatExporter/development/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/dharni/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.44.0-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/dharni/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.44.0-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.44.0 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/dharni/WeChatExporter/development/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
node-pre-gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/dharni/WeChatExporter/development/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/dharni/WeChatExporter/development/node_modules/sqlite3
node-pre-gyp ERR! node -v v13.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute 'nw-gyp configure --fallback-to-build --module=/Users/dharni/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.44.0-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/dharni/WeChatExporter/development/node_modules/sqlite3/lib/binding/node-webkit-v0.44.0-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-webkit-v0.44.0 --python=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7' (Error: spawn nw-gyp ENOENT)
npm WARN WechatExporter@1.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@1.3.1 (node_modules/7zip-bin-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.3.1: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dharni/.npm/_logs/2020-01-17T09_44_21_648Z-debug.log

**Comment by jaykangta** [comment]
我也是same问题，感觉好像是node太新了不支持了?

**Comment by Karl-Han** [comment]
你们试一下复制黏贴这条指令运行一下，就知道没有装nw-gyp了。
解决方法就是 `npm install -g nw-gyp`
